# Generated by Django 4.0.1 on 2022-01-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApi', '0006_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sku',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
