# Generated by Django 4.0.1 on 2022-01-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApi', '0007_rename_sku_item_product_remove_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='glove', max_length=60),
            preserve_default=False,
        ),
    ]
