# Generated by Django 4.0.1 on 2022-01-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApi', '0008_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
