# Generated by Django 4.0.1 on 2022-01-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApi', '0009_alter_item_serial_number_alter_warehouse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
